// components/About.tsx
import styles from './About.module.css';
import Image from './Image';

export default function About() {
  const now = new Date().getFullYear();
  const experience = now - 2017;
  const icoSizePx = 40;
  return (
    <div className={`container`} style={{ padding: '50px' }}>
      <div className={`row justify-content-center`}>
        <Image
          src={`/images/me.webp`}
          alt={`Lukas Forst`}
          height={`300px`}
          width={`300px`}
        />
      </div>
      <div className={`row justify-content-center`} style={{
        fontSize: '3rem',
        fontWeight: 'bold'
      }}>
        Lukas Forst
      </div>
      <div className={`row`}>
        <div className={`col ${styles.socialContainer}`}>
          <a className={styles.socialButton}
             href={'https://github.com/LukasForst'}
             target={'_blank'}
             rel={'noreferrer'}
          >
            <Image
              src={'/images/github.webp'}
              height={icoSizePx}
              width={icoSizePx}
              alt={'Github icon.'}
            />
          </a>
          <a className={styles.socialButton}
             href={'mailto:lukas@forst.dev'}
          >
            <Image
              src={'/images/email.webp'}
              height={icoSizePx}
              width={icoSizePx}
              alt={'Email icon.'}
            />
          </a>
          <a className={styles.socialButton}
             href={'https://www.linkedin.com/in/lukas-forst'}
             target={'_blank'}
             rel={'noreferrer'}
          >
            <Image
              src={'/images/ln.webp'}
              height={icoSizePx}
              width={icoSizePx}
              alt={'LinkedIn icon.'}
            />
          </a>
        </div>
      </div>
      <div className={`row justify-content-evenly`}>
        <div className={`col ${styles.textBlock}`}>
          {`
          I'm a motivated and self-driven Software Engineer with in-depth knowledge of Kotlin,
          Software Architecture and passion for functional programming all the way
          from the lambda calculus through Haskell to the Kotlin & JavaScript.
          I love designing and implementing one-click DevOps and have a strong
          experience in architecture design (including PaaS, SaaS) as well as mathematical
          background ranging from group theory, data analysis, AI utilization,
          predictions to mathematical optimization. I have strong experience in software engineering,
          software architecture, client-facing, and leading projects from technical side.
          `}
        </div>
        <div className={`col ${styles.textBlock}`}>
          {`
          I'm currently pursuing a Cyber Security Master's degree at CTU, more specifically in Stratosphere Research Laboratory.
          I started my career in the Prague-based AI startup Blindspot Solutions and then moved to a cyber-security startup in
          Berlin - Wire. At the beginning of 2020, I co-founded a medical AI startup, Mild Blue,
          where I'm responsible for the products and company security.
          As of ${now}, I have ${experience} years of experience building production-ready software.
          `}
        </div>
      </div>
    </div>
  );
}

// src/componenets/About.vue
<template>
  <div class="about-container">
    <div class="about">
      <p class="about-text md-body-2">
        I'm a motivated and self-driven Software Engineer with in-depth knowledge of Kotlin,
        Software Architecture and passion for functional programming all the way
        from the lambda calculus through Haskell to the Kotlin & JavaScript.
        I love designing and implementing one-click DevOps and have a strong
        experience in architecture design (including PaaS, SaaS) as well as mathematical
        background ranging from group theory, data analysis, AI utilization,
        predictions to mathematical optimization. I have strong experience in software engineering,
        software architecture, client-facing, and leading projects from technical side.
      </p>
      <p class="about-text md-body-2">
        I'm currently pursuing a Cyber Security Master's degree at CTU, more specifically in Stratosphere Research Laboratory.
        I started my career in the Prague-based AI startup Blindspot Solutions and then moved to a cyber-security startup in
        Berlin - Wire. At the beginning of 2020, I co-founded a medical AI startup, Mild Blue,
        where I'm responsible for the products and company security.
        As of {{ thisYear }}, I have {{ experience }} years of experience building production-ready software.
      </p>
    </div>
  </div>

</template>

<script>
export default {
  name: 'About',
  data() {
    const now = new Date().getFullYear();
    const experience = now - 2017;
    return {
      thisYear: now,
      experience: experience
    };
  }

};
</script>

<style scoped>
.about-container {
  display: flex;
  justify-content: center;
  padding: 50px;
}

.about {
  /*about-text * 2 + 100px in between*/
  max-width: 1100px;

  display: flex;
  justify-content: space-evenly;
  flex-grow: 1;
  flex-wrap: wrap;
}

.about-text {
  max-width: 500px;
}

p {
  line-height: 2.2;
  font-size: 15px;
  /*noinspection CssFloatPxLength*/
  letter-spacing: .1px;
  text-align: justify;

}
</style>
